<?php

namespace AppBundle\Repository;

/**
 * CharApiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharApiRepository extends \Doctrine\ORM\EntityRepository
{
}
