<?php

namespace AppBundle\Repository;

/**
 * ItemGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
