<?php

namespace AppBundle\Repository;

/**
 * LoginCcpCallBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginCcpCallBackRepository extends \Doctrine\ORM\EntityRepository
{
}
